%YAML 1.2
---
$id:                      resource
type:                     object
---
$id:                      error
type:                     object
---
$id:                      meta
type:                     object
---
$id:                      links
type:                     object
